name: New limerick
description: Submit your gravitational-wave limerick
title: "[issue title]: A new limerick submission"
labels: ["limerick"]
projects: ["gwlimericks"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Fill in the details below and press "Create" to submit your limerick.
  - type: textarea
    id: limerick
    attributes:
      label: Your limerick
      description: Add your limerick here
      placeholder: .
      value: "My limerick..."
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Your name
      description: as you would like it to appear next to your limerick
      placeholder: 
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your email address
      description: in case we need to contact you about your limerick
      placeholder: 
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title of your limerick
      description: You don't need a title for your limerick, but if you would like to include one, add it here
      placeholder: 
    validations:
      required: false
      
